#### Question 1

In [11]:
## Load Required Pacackages
# Import pandas for reading datasets
import pandas as pd
# Import numpy for any computation-like processes
import numpy as np
# Import matplotlib for any graphs
import matplotlib.pyplot as plt
# Import train_test_split from sklearn
from sklearn.model_selection import train_test_split
# Import grid search 
from sklearn.model_selection import GridSearchCV
# Import simple imputer 
from sklearn.impute import SimpleImputer
# Import MinMax scaler for normalization
from sklearn.preprocessing import MinMaxScaler
# Import pipline
from sklearn.pipeline import Pipeline
# Import r2_score for evaluting regression
from sklearn.metrics import r2_score
# Import KNN classifier
from sklearn.neighbors import KNeighborsClassifier
# Import KNN regressor
from sklearn.neighbors import KNeighborsRegressor

#1. model
from sklearn.tree import DecisionTreeClassifier as dtc
#2. data
from sklearn.datasets import load_breast_cancer
#3. val
from sklearn.metrics import accuracy_score, balanced_accuracy_score

In [14]:
X = load_breast_cancer().data
y = load_breast_cancer().target
X, y

(array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0,

In [10]:
# Split into training and testing subsets with stratification over y
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state=42, stratify=y)

In [ ]:
dtc = dtc(random_state=42)
dtc.fit(X_train, y_train)
pred = dtc.predict(X_test)
print(f"model accuracy: {accuracy_score(y_test, pred)}")
print(f"model balanced accuracy: {balanced_accuracy_score(y_test, pred)}")

model accuracy: 0.9210526315789473
model balanced accuracy: 0.9226190476190477


In [17]:
param_grid = {
    'criterion': ['gini', 'entropy', 'log_loss'],
    'max_depth': [None, 3, 5, 7, 10],
    'min_samples_split': [2, 5, 10, 20],
    'min_samples_leaf': [1, 2, 5, 10]
}

dtc_gs = GridSearchCV(
    estimator=dtc,
    param_grid=param_grid,
    cv=5,            # 5-fold cross validation
    scoring='accuracy',
    n_jobs=-1        # use all cores
)

In [18]:
# Fit the GridSearchCV object
dtc_gs.fit(X, y)

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(), n_jobs=-1,
             param_grid={'criterion': ['gini', 'entropy', 'log_loss'],
                         'max_depth': [None, 3, 5, 7, 10],
                         'min_samples_leaf': [1, 2, 5, 10],
                         'min_samples_split': [2, 5, 10, 20]},
             scoring='accuracy')

In [19]:
print("Best Parameters:", dtc_gs.best_params_)
print("Best Cross-Validation Accuracy:", dtc_gs.best_score_)

Best Parameters: {'criterion': 'entropy', 'max_depth': 5, 'min_samples_leaf': 5, 'min_samples_split': 5}
Best Cross-Validation Accuracy: 0.943766495885732


#### Question 2 

In [20]:
# Read dataset
bankdata = pd.read_csv('bill_authentication.csv')
# View the head
bankdata.head()

Variance  Skewness  Curtosis  Entropy  Class
0   3.62160    8.6661   -2.8073 -0.44699      0
1   4.54590    8.1674   -2.4586 -1.46210      0
2   3.86600   -2.6383    1.9242  0.10645      0
3   3.45660    9.5228   -4.0112 -3.59440      0
4   0.32924   -4.4552    4.5718 -0.98880      0

In [21]:
# Show dataset info
bankdata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1372 entries, 0 to 1371
Data columns (total 5 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   Variance  1372 non-null   float64
 1   Skewness  1372 non-null   float64
 2   Curtosis  1372 non-null   float64
 3   Entropy   1372 non-null   float64
 4   Class     1372 non-null   int64  
dtypes: float64(4), int64(1)
memory usage: 53.7 KB


In [22]:
# Split the data into predictors and output
X = bankdata.drop('Class', axis = 1)
y = bankdata['Class']

In [23]:
# Split the data into train and test subsets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.25, random_state = 43)

In [27]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(
    n_estimators=100,     
    max_depth=None,        
    random_state=42
)

In [29]:
rf.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [30]:
# Use classifier to make predictions
y_pred = rf.predict(X_test)

In [31]:
# Print classification report and confusion matrix
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[192   3]
 [  1 147]]
              precision    recall  f1-score   support

           0       0.99      0.98      0.99       195
           1       0.98      0.99      0.99       148

    accuracy                           0.99       343
   macro avg       0.99      0.99      0.99       343
weighted avg       0.99      0.99      0.99       343



In [35]:
param_grid = {
    'n_estimators': [100, 200, 300],      
    'max_depth': [None, 5, 10, 20],       
    'min_samples_split': [2, 5, 10],      
    'min_samples_leaf': [1, 2, 4],        
    'max_features': ['sqrt', 'log2']     
}

rf_gs = GridSearchCV(
    estimator=rf,
    param_grid=param_grid,
    cv=3,            
    scoring='accuracy',
    n_jobs=-1,       
    verbose=1        
)

In [ ]:
rf_gs.fit(X, y)

Fitting 3 folds for each of 216 candidates, totalling 648 fits


In [ ]:
# Print the tuned parameters and score
print("Tuned SVM Parameters: {}".format(rf_gs.best_params_))
print("Best score is {}".format(rf_gs.best_score_))

Tuned SVM Parameters: {'C': 3, 'kernel': 'rbf'}
Best score is 1.0


In [ ]:
from sklearn.metrics import classification_report, confusion_matrix
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))